import "../styles/globals.css";
import Background from "@/components/Background";

export const metadata = {
  title: "Walk that Duck",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="">{children}</main>
        <Background />
      </body>
    </html>
  );
}
