import "../styles/globals.css";
import BackgroundLines from "@/components/BackgroundLines";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <BackgroundLines />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
